---
title: "Assignment 3"
author: "Alex Takoudes"
date: "2023-01-12"
output: html_document
---
***
### 1. Suppose x = 1.1, a = 2.2, and b = 3.3. Assign each expression to the variable z and print the value stored in each z.

```{r}
x <- 1.1
a <- 2.2
b <- 3.3

#a
z <- x^a^b
z

#b
z <- (x^a)^b
z

#c
z <- 3*(x^3)+2*(x^2)+1
z
```

### 2. Using the `rep` and `seq` functions, create the following vectors:

```{r}
#a
c(seq(from=1, to=8), seq(from=7, to=1))
#OR more efficiently:
c(1:8,7:1)

#b
rep(1:5, c(1:5))

#c
rep(5:1, c(1:5))
```

### 3. Create a vector using the code: queue <- c("sheep", "fox", "owl", "ant"), where queue represents the animals that are lined up to enter an exclusive club, with the sheep at the front of the line. Using R expressions, update queue as:

```{r}
queue <- c("sheep", "fox", "owl", "ant")

#a the serpent arrives and gets in the back of the line;
queue <- c(queue, "serpent")
queue

#b the sheep enters the club (so disappears from the line);
queue <- queue[2:5]
queue

#c the donkey arrives and talks his way to the front of the line;
queue <- c("donkey", queue)
queue

#d the serpent gets impatient and leaves;
queue <- queue[1:4]
queue

#e the aphid arrives and the ant invites him to cut in line (hint: check out the append function).
queue <- append(queue, "aphid", after=3)
queue

#f Finally, determine the position of the aphid in the line (hint: use the which function).
which(queue=="aphid")
```