---
title: "Assignment 8"
author: "Alex Takoudes"
date: "2023-01-26"
output: html_document
---

## Code Reflection: Weekly Assignment 2

```{r}
set.seed(123)

##################################################
# FUNCTION: datagen 
# generates a two column data frame of data.
# inputs:
#   c_mean: mean value for normal distribution of control data
#   c_sd: standard deviation value for normal distribution of control data
#   t_mean: mean value for normal distribution of treatment data
#   t_sd: standard deviation value for normal distribution of treatment data
#   nrows: number of rows of data
# outputs: 2 column matrix nrows long with half control data and half treatment data
#------------------------------------------------- 
datagen <- function(c_mean=10, c_sd=1.5, t_mean=45, t_sd=2, n=25){ #nrows as default argument might be better as "n"
  dFrame <- data.frame(
    Type = rep(c("Control", "Treatment"),each=n), 
    Value =  c(control = rnorm(n, mean=c_mean, sd=c_sd),
               treatment = rnorm(n, mean=t_mean, sd=t_sd)
               )
    )
  return(dFrame)
}

# One difference with my code is that I used number of rows as an argument. It might have been better to use the number of samples as this would be an easier number to come up with. Another difference is that my data frame creates the elements Type and Value directly. I'm not sure which is cleaner, but when it comes to troubleshooting, it might have been easier to have the Type and Value definitions outside of the dataframe.

##################################################

data <- datagen() #default values
data2 <- datagen(5, 3, 90, 4) #change the means and standard deviations

head(data)
head(data2) #looks like it works

##################################################
# FUNCTION: psearch
# returns the pvalue of a given two column dataframe
# inputs:
#   df: dataframe to be analyzed
# outputs: pvalue of two column data frame
#------------------------------------------------- 
psearch <- function(df=NULL){
  if(is.null(df)){
    df <- datagen()
  }
  summary <- summary(aov(data[[2]]~data[[1]], data=df))
  pvalue <- summary[[1]][["Pr(>F)"]][[1]] #go into the summary list and find the P value. Only take the first value out of P because P[[2]] is NA 
  return(pvalue)
}

# My code is different from the solution because it does the summary and the test in one line. For reproducibility purposes, it might have been better to save the test as a new variable and then make a summary of it on the next line. When it comes to the test, I called the variables by sub-setting the data frame which might be more reproducible than the solutions where they are called by row name. Although it doesn't really matter as long as the column names don't change.

# I also added an "if" statement at the beginning which will call the datagen functin to create a dataframe in case the user does not input any data.
##################################################

psearch(data)
```

## Code Reflection: [Assignment 6](Assignment6.html)
* Click link to view annotations

## Code Annotation Practice

```{r}
## Set up libraries
library(tidyverse)
library(ggthemes)


# Data obtained from Veysey Powell and Babbitt 2016: An experimental test of buffer utility as a technique for managing pool-breeding amphibians https://datadryad.org/stash/dataset/doi:10.5061%2Fdryad.547rp

dryadData <- read.table("/Users/alextakoudes/Desktop/Classes/BIOL1007/doi_10/veysey powell and babbitt_data_buffers and amphibians2.csv", header=TRUE, sep=",", stringsAsFactors = TRUE)

 glimpse(dryadData)
 head(dryadData)
 table(dryadData$species)

dryadData$species<-factor(dryadData$species, labels=c("Spotted Salamander", "Wood Frog")) #creating 'labels' to use for the plot

#class(dryadData$treatment)
dryadData$treatment <- factor(dryadData$treatment, 
            levels=c("Reference",
                     "100m", "30m"))


p<- ggplot(data=dryadData, 
       aes(x=interaction(wetland, treatment), 
           y=count.total.adults, fill=factor(year))) + geom_bar(position="dodge", stat="identity", color="black") +
  ylab("Number of breeding adults") +
  xlab("") +
  scale_y_continuous(breaks = c(0,100,200,300,400,500)) +
  scale_x_discrete(labels=c("30 (Ref)", "124 (Ref)", "141 (Ref)", "25 (100m)","39 (100m)","55 (100m)","129 (100m)", "7 (30m)","19 (30m)","20 (30m)","59 (30m)")) +
  facet_wrap(~species, nrow=2, strip.position="right") +
  theme_few() + scale_fill_grey() + 
  theme(panel.background = element_rect(fill = 'gray94', color = 'black'), legend.position="top",  legend.title= element_blank(), axis.title.y = element_text(size=12, face="bold", colour = "black"), strip.text.y = element_text(size = 10, face="bold", colour = "black")) + 
  guides(fill=guide_legend(nrow=1,byrow=TRUE)) 

p
```